//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mzh.Public.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class bsp_groupdetails
    {
        public int groupdetailid { get; set; }
        public int groupid { get; set; }
        public int uid { get; set; }
        public int sno { get; set; }
        public Nullable<System.DateTime> paytime { get; set; }
        public Nullable<bool> isgetcoupon { get; set; }
    }
}
