//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mzh.Public.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class bsp_groups
    {
        public int groupid { get; set; }
        public int grouptype { get; set; }
        public int groupoid { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public int startuid { get; set; }
        public decimal groupprice { get; set; }
        public Nullable<decimal> shopprice { get; set; }
        public Nullable<bool> isfinish { get; set; }
        public int needcount { get; set; }
        public int nowcount { get; set; }
        public Nullable<bool> isfail { get; set; }
        public int failtype { get; set; }
        public int maxtime { get; set; }
    
        public virtual bsp_groupdetails bsp_groupdetails { get; set; }
    }
}
