//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mzh.Public.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class bsp_users
    {
        public int uid { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
        public string password { get; set; }
        public short userrid { get; set; }
        public short admingid { get; set; }
        public string nickname { get; set; }
        public string avatar { get; set; }
        public int paycredits { get; set; }
        public int rankcredits { get; set; }
        public byte verifyemail { get; set; }
        public byte verifymobile { get; set; }
        public System.DateTime liftbantime { get; set; }
        public string salt { get; set; }
        public string username { get; set; }
        public string openid { get; set; }
        public int gender { get; set; }
    }
}
