//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mzh.Public.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class brnshopEntities : DbContext
    {
        public brnshopEntities()
            : base("name=brnshopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bsp_admingroups> bsp_admingroups { get; set; }
        public virtual DbSet<bsp_adminoperatelogs> bsp_adminoperatelogs { get; set; }
        public virtual DbSet<bsp_adminusers> bsp_adminusers { get; set; }
        public virtual DbSet<bsp_advertpositions> bsp_advertpositions { get; set; }
        public virtual DbSet<bsp_adverts> bsp_adverts { get; set; }
        public virtual DbSet<bsp_attributegroups> bsp_attributegroups { get; set; }
        public virtual DbSet<bsp_attributes> bsp_attributes { get; set; }
        public virtual DbSet<bsp_attributevalues> bsp_attributevalues { get; set; }
        public virtual DbSet<bsp_bannedips> bsp_bannedips { get; set; }
        public virtual DbSet<bsp_banners> bsp_banners { get; set; }
        public virtual DbSet<bsp_brands> bsp_brands { get; set; }
        public virtual DbSet<bsp_browsehistories> bsp_browsehistories { get; set; }
        public virtual DbSet<bsp_businesses> bsp_businesses { get; set; }
        public virtual DbSet<bsp_businessimgs> bsp_businessimgs { get; set; }
        public virtual DbSet<bsp_buysendproducts> bsp_buysendproducts { get; set; }
        public virtual DbSet<bsp_buysendpromotions> bsp_buysendpromotions { get; set; }
        public virtual DbSet<bsp_categories> bsp_categories { get; set; }
        public virtual DbSet<bsp_couponproducts> bsp_couponproducts { get; set; }
        public virtual DbSet<bsp_coupons> bsp_coupons { get; set; }
        public virtual DbSet<bsp_coupontypes> bsp_coupontypes { get; set; }
        public virtual DbSet<bsp_creditlogs> bsp_creditlogs { get; set; }
        public virtual DbSet<bsp_eventlogs> bsp_eventlogs { get; set; }
        public virtual DbSet<bsp_favorites> bsp_favorites { get; set; }
        public virtual DbSet<bsp_filterwords> bsp_filterwords { get; set; }
        public virtual DbSet<bsp_fullcutproducts> bsp_fullcutproducts { get; set; }
        public virtual DbSet<bsp_fullcutpromotions> bsp_fullcutpromotions { get; set; }
        public virtual DbSet<bsp_fullsendproducts> bsp_fullsendproducts { get; set; }
        public virtual DbSet<bsp_fullsendpromotions> bsp_fullsendpromotions { get; set; }
        public virtual DbSet<bsp_giftpromotions> bsp_giftpromotions { get; set; }
        public virtual DbSet<bsp_gifts> bsp_gifts { get; set; }
        public virtual DbSet<bsp_loginfaillogs> bsp_loginfaillogs { get; set; }
        public virtual DbSet<bsp_news> bsp_news { get; set; }
        public virtual DbSet<bsp_newstypes> bsp_newstypes { get; set; }
        public virtual DbSet<bsp_oauth> bsp_oauth { get; set; }
        public virtual DbSet<bsp_onlinetime> bsp_onlinetime { get; set; }
        public virtual DbSet<bsp_onlineusers> bsp_onlineusers { get; set; }
        public virtual DbSet<bsp_orderactions> bsp_orderactions { get; set; }
        public virtual DbSet<bsp_orderproducts> bsp_orderproducts { get; set; }
        public virtual DbSet<bsp_orderrefunds> bsp_orderrefunds { get; set; }
        public virtual DbSet<bsp_orderreviews> bsp_orderreviews { get; set; }
        public virtual DbSet<bsp_orders> bsp_orders { get; set; }
        public virtual DbSet<bsp_productattributes> bsp_productattributes { get; set; }
        public virtual DbSet<bsp_productconsults> bsp_productconsults { get; set; }
        public virtual DbSet<bsp_productconsulttypes> bsp_productconsulttypes { get; set; }
        public virtual DbSet<bsp_productimages> bsp_productimages { get; set; }
        public virtual DbSet<bsp_productkeywords> bsp_productkeywords { get; set; }
        public virtual DbSet<bsp_productreviewquality> bsp_productreviewquality { get; set; }
        public virtual DbSet<bsp_productreviews> bsp_productreviews { get; set; }
        public virtual DbSet<bsp_products> bsp_products { get; set; }
        public virtual DbSet<bsp_productskus> bsp_productskus { get; set; }
        public virtual DbSet<bsp_productstats> bsp_productstats { get; set; }
        public virtual DbSet<bsp_productstocks> bsp_productstocks { get; set; }
        public virtual DbSet<bsp_regions> bsp_regions { get; set; }
        public virtual DbSet<bsp_relateproducts> bsp_relateproducts { get; set; }
        public virtual DbSet<bsp_searchhistories> bsp_searchhistories { get; set; }
        public virtual DbSet<bsp_shipaddresses> bsp_shipaddresses { get; set; }
        public virtual DbSet<bsp_signproducts> bsp_signproducts { get; set; }
        public virtual DbSet<bsp_singlepromotions> bsp_singlepromotions { get; set; }
        public virtual DbSet<bsp_suitproducts> bsp_suitproducts { get; set; }
        public virtual DbSet<bsp_suitpromotions> bsp_suitpromotions { get; set; }
        public virtual DbSet<bsp_timeproducts> bsp_timeproducts { get; set; }
        public virtual DbSet<bsp_topics> bsp_topics { get; set; }
        public virtual DbSet<bsp_useraddrs> bsp_useraddrs { get; set; }
        public virtual DbSet<bsp_userdetails> bsp_userdetails { get; set; }
        public virtual DbSet<bsp_userranks> bsp_userranks { get; set; }
        public virtual DbSet<bsp_pvstats> bsp_pvstats { get; set; }
        public virtual DbSet<bsp_navs> bsp_navs { get; set; }
        public virtual DbSet<bsp_adminactions> bsp_adminactions { get; set; }
        public virtual DbSet<bsp_boxbookes> bsp_boxbookes { get; set; }
        public virtual DbSet<bsp_boxes> bsp_boxes { get; set; }
        public virtual DbSet<bsp_friendlinks> bsp_friendlinks { get; set; }
        public virtual DbSet<bsp_helps> bsp_helps { get; set; }
        public virtual DbSet<bsp_cateproducts> bsp_cateproducts { get; set; }
        public virtual DbSet<bsp_files> bsp_files { get; set; }
        public virtual DbSet<bsp_users> bsp_users { get; set; }
    }
}
